version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: agendaale-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: agendaale_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: agendaale-mq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpassword
    ports:
      - "5672:5672"  
      - "15672:15672"
    restart: unless-stopped